version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "7776:7776"
    environment:
      - ENV=production
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "7777:7777"
